config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'public#index'

  resources :advices, :only => [:show, :new, :create] do
    collection do
      get :random
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/advice.rb
class Advice < ActiveRecord::Base
  validates :text, presence: true
end

app/controllers/advices_controller.rb
class AdvicesController < ApplicationController
  helper_method :advice

  def new
    @advice = Advice.new
  end

  def show
    @advice = Advice.find(params[:id])
  end

  def random
    advice = Advice.find(random_advice_id(params[:id]))

    render :json => advice
  end

  def create
    advice = Advice.new(params.require(:advice).permit(:text))
    advice.state = 'pending_review'
    advice.save!

    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :random_advice_id

  def random_advice_id(other_id = nil)
    chain = Advice.order('RANDOM()').where(:state => 'accepted')
    chain = chain.where('id != (?)', other_id) if other_id.present?

    chain.first.id
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  protected

  def advice
    @advice ||= Advice.find(random_advice_id)
  end
  helper_method :advice
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/advices/_advice.html.haml
= render partial: 'shared/header'
- content_for(:meta_social) do
  - advice_text = advice.text
  - site_title = 'Good Fucking Austerity Advice'
  - url = advice_url(:id => advice.id)

  %meta{:property => 'og:title', :content => advice_text}
  %meta{:property => 'og:type', :content => 'website'}
  %meta{:property => 'og:url', :content => url}
  %meta{:property => 'og:description', :content => site_title}

  %meta{:property => 'twitter:card', :content => 'summary'}
  %meta{:property => 'twitter:site', :content => '@good_faa'}
  %meta{:property => 'twitter:title', :content => site_title}
  %meta{:property => 'twitter:description', :content => advice_text}
  %meta{:property => 'twitter:url', :content => url}
.container
  %h1#fucking-advice.fucking-advice= advice.text
  = link_to("This isn't enough, I need more advice.", random_advices_path(:id => advice.id), :class => 'more-advice', :remote => true)
  .social
    %span{:class => 'st_twitter', :st_title => "#{advice.text} - #{advice_url(:id => advice.id)} #austerity"}
    %span{:class => 'st_facebook'}
= render partial: 'shared/navigation'

app/views/advices/_navigation.html.haml
.navigation
  = link_to('I want to suggest advice', new_advice_path)
  %span.separator= '|'
  = link_to('Home', root_path)
  %span.separator= '|'
  = link_to('About', 'https://github.com/marionzualo/gfaa', target: '_blank')

app/views/advices/new.html.haml
= render partial: 'shared/header'
.container
  %h2 I want to suggest advice
  %p Here you can suggest a good fucking austerity advice to add to this website.
  %p These suggestions will be reviewed and published only if appropriate. Some tips:
  %ul
    %li It should be connected with the theme: good fucking austerity advice;
    %li it should not be long.
  %p Thank you for suggesting!

  = form_for @advice, url: {action: 'create'} do |form|
    .row
      .two-thirds.column
        = form.label :text, 'Advice'
        = form.text_field :text, :class => 'u-full-width', :required => ''
        = form.submit 'Suggest', :class => 'button-primary'
= render partial: 'shared/navigation'

app/views/advices/show.html.haml
= render partial: 'advice', :locals => { :advice => @advice }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Good Fucking Austerity Advice
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    - description = 'A compilation of the best austerity advice on the planet.'
    - title = 'Good Fucking Austerity Advice'
    - url = 'http://www.goodfuckingausterityadvice.com/'
    %meta{:name => 'description', :content => description}
    -# Open graph social share meta tags
    - if content_for?(:meta_social)
      = yield(:meta_social)
    - else
      %meta{:property => 'og:title', :content => title}
      %meta{:property => 'og:type', :content => 'website'}
      %meta{:property => 'og:url', :content => url}
      %meta{:property => 'og:description', :content => description}

      %meta{:property => 'twitter:card', :content => 'summary'}
      %meta{:property => 'twitter:site', :content => '@good_faa'}
      %meta{:property => 'twitter:title', :content => title}
      %meta{:property => 'twitter:description', :content => description}
      %meta{:property => 'twitter:url', :content => url}
    %script{:type => "text/javascript", :src => "http://w.sharethis.com/button/buttons.js"}
    %script{:type => "text/javascript"}
      stLight.options({publisher: "cc3718df-34ba-4cc4-8100-ec85a3b099ec", doNotHash: false, doNotCopy: false, hashAddressBar: false});
  %body
    = yield

app/views/shared/_header.html.haml
.header
  %span
    Good Fucking Austerity Advice
  ='- Serving the working class policy maker since 2008.'

app/views/shared/_navigation.html.haml
.navigation
  = link_to('I want to suggest advice', new_advice_path)
  %span.separator= '|'
  = link_to('About', 'https://github.com/marionzualo/gfaa', target: '_blank')